name: "Kensan-project"
services:
  opcua:
    build: ./opcua-server
    ports:
      - "4840:4840"

  frontend:
    build: ./frontend/kensan
    container_name: kensan_frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    
  backend:
    build: ./backend
    ports:
      - "3000:3000"